language: node_js
node_js:
  - '10'
install:
  - npm ci
before_script:
  - npm run build:lib
script:
  - npm run test -- --code-coverage --watch=false
before_deploy:
  - npm run copy:readme
  - cd dist/ngx-translate-module-loader
deploy:
  provider: npm
  edge: true
  email: '$NPM_EMAIL'
  api_key: '$NPM_API_TOKEN'
  skip_cleanup: true
  on:
    tags: true
