language: node_js
node_js:
  - '10'
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
before_install:
  - if [[ $TRAVIS_COMMIT_MESSAGE == *"[Travis]"* ]] && [ -z $TRAVIS_TAG ]; then travis_terminate 0; fi
install:
  - npm ci
script:
  - npm run test -- --code-coverage --watch=false
after_script:
  - chmod +x scripts/update-version.sh
  - scripts/update-version.sh
before_deploy:
  - npm run build:lib
  - npm run copy:readme
  - cd dist/ngx-translate-module-loader
deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_API_TOKEN'
  skip_cleanup: true
  on:
    tags: true
