name: 'feature'

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - '*'
      - '!master'
      - '!v*.'
      - '!*.*.*'

jobs:
  lib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install packages
        run: npm ci --ignore-scripts
      - name: Build lib & app
        run: |
          npm run build:lib
          npm run build
      - name: Unit test
        run: npm run test:ci
