name: 'master'

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'

jobs:
  lib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install packages
        run: npm ci --ignore-scripts
      - name: Unit test
        run: |
          npm run test:ci
          $(npm bin)/codecov -f coverage/*.json
      - name: Build lib & app
        run: |
          npm run build:lib
          npm run build
      - if: startsWith(github.ref, 'refs/tags/v')
        name: Upload lib
        uses: actions/upload-artifact@v2
        with:
          name: ngx-translate-module-loader
          path: dist/ngx-translate-module-loader

  npm:
    needs:
      - lib
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Download lib
        uses: actions/download-artifact@v2
        with:
          name: ngx-translate-module-loader
          path: /tmp/ngx-translate-module-loader
      - name: Publish lib
        run: |
          cd /tmp/ngx-translate-module-loader
          ls -ltra .
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
